name:                drawadt
version:             0.1.0.0
github:              "roger-uw/drawadt"
license:             BSD3
author:              "Rongxiao Fu"
maintainer:          "furongxiao@outlook.com"
copyright:           "2019 Rongxiao Fu"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/roger-uw/drawadt#readme>

dependencies:
- base >= 4.7 && < 5
- mtl
- ListLike
- vec
- fin

library:
  source-dirs: src
  ghc-options:
    - -O2

tests:
  drawadt-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - drawadt
    - text
    - recursion-schemes
    - deepseq
